#pragma once

/* System stuff */
#define MPCORE_ENTRY (0x1FFFFFFC)
#define FIRMSTUB_LOC (0x1FFFFC00)
#define MPCORE_PMR   (0x17E00000)


/* VRAM / Framebuffer */
#define SCREEN_HEIGHT    (240)
#define SCREEN_TOP_WIDTH (400)
#define SCREEN_BOT_WIDTH (320)

#define VRAM_TOP_DIM    (SCREEN_TOP_WIDTH * SCREEN_HEIGHT)
#define VRAM_BOTTOM_DIM (SCREEN_BOT_WIDTH * SCREEN_HEIGHT)

#define VRAM_START (0x18000000)
#define VRAM_SIZE  (0x00600000)
#define VRAM_END   (VRAM_START + VRAM_SIZE)

#define VRAM_DEF_TOPLEFT  (VRAM_START + (VRAM_SIZE/2))
#define VRAM_DEF_TOPRIGHT (VRAM_DEF_TOPLEFT + VRAM_TOP_DIM * 3)
#define VRAM_DEF_BOTTOM   (VRAM_DEF_TOPRIGHT + VRAM_TOP_DIM * 3)
