#pragma once

#define SCREEN_HEIGHT    (240)
#define SCREEN_TOP_WIDTH (400)
#define SCREEN_BOT_WIDTH (320)

#define VRAM_TOP_SIZE (SCREEN_TOP_WIDTH * SCREEN_HEIGHT)
#define VRAM_BOT_SIZE (SCREEN_BOT_WIDTH * SCREEN_HEIGHT)

#define VRAM_START (0x18000000)
#define VRAM_SIZE  (0x00600000)
#define VRAM_END   (VRAM_START + VRAM_SIZE)

#define VRAM_DEF_TOPLEFT  (VRAM_START)
#define VRAM_DEF_TOPRIGHT (VRAM_DEF_TOPLEFT + VRAM_TOP_SIZE * 3)
#define VRAM_DEF_BOTTOM   (VRAM_DEF_TOPRIGHT + VRAM_TOP_SIZE * 3)
